version: "3.8"
services:

  front-end:
    build: ./front-end
    ports:
      - 3000:80
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - back-end
    env_file:
      - ./front-end/.env

  back-end:
    build: ./back-end
    ports:
      - 3001:3001
    env_file:
      - ./back-end/.env
    volumes:
      - ./uploads:/uploads