name: CI/CD Pipeline

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (for front-end)
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install front-end dependencies
        working-directory: ./front-end
        run: npm install

      - name: Install back-end dependencies
        working-directory: ./back-end
        run: npm install

      - name: Run back-end tests
        working-directory: ./back-end
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            npm test
          fi

      - name: Build and run Docker containers
        run: docker-compose up --build
