name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy React and Express App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd 4-final-project-group-bill-splitting-app
            git pull
            cd front-end
            npm install
            npm start
            cd ../back-end
            npm install
            npm start
            echo 'Success'
