# test
name: Node.js CI 

on:
  push:
    branches: [ "master", "workflows-action" ]
  pull_request:
    branches: [ "master", "workflows-action" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm run install-deps
    
     - name: Lint
      run: npm run lint
      
    - name: Run Tests
      run: npm run test
      
    - name: Build Frontend
      run: |
        cd front-end
        npm run build